name = "GenDav"
uuid = "0c603acf-41d5-40bf-a378-7dbbea0dae82"
authors = ["Simon Neville"]
version = "1.0.0-DEV"

[compat]
julia = "1.11.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
